#!/bin/bash
# this script compresses kryoflux stream folders by collection number.

BLUE='\033[0;36m'
GREEN='\033[1;32m'
RED='\033[0:31m'
NC='\033[0m'

echo -e  "${BLUE}Please enter your collection number to initiate tar creation.${NC}"

read collnum

for f in 'find . -maxdepth 1 -mindepth 1 -type d -name "$collnum-*"'; do 
'-exec gtar cvf {}.tar {} \;'

done

echo -e "${GREEN}Kryoflux stream files have been compressed.${NC}"
